name: Maven Publish to Central

on:
  workflow_dispatch:

jobs:
  build:
    env:
      GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: central
        server-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}

    - name: Build with Maven
      run: mvn clean deploy
