name: Maven Publish to Central

on:
  workflow_dispatch:

jobs:
  build:
    env:
      GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
      GITHUB_ACTOR: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: central
#        gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY }}

    - name: Output Settings.xml
      run: cat ~/.m2/settings.xml

    - name: Output Settings.xml 2
      run: echo ${env.GITHUB_ACTOR}

    - name: Build with Maven
      run: mvn -X clean deploy

